default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: ahm_test

development:
  <<: *default
  database: ahm_development
